[package]
name = "parse_ocr_tracker"
version = "0.1.0"
edition = "2021"

build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.4"
walkdir = "2.5.0"
serde = "1.0.197"